#
# conda env create -f spot_conda_environment.yml
#
name: spot
dependencies:
  - python=3.11
  - pip
  - ephem
  - astropy
  - scipy
  - matplotlib
  - pillow
  - pyqt
  - python-dateutil
  - pyyaml
  - qtpy
  - requests
  - ply
  - pytz
 